AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  user-service

  SAM Template for user-service

Parameters:
  FirebaseApiKey:
    Type: String
  FirebaseAuthDomain:
    Type: String
  FirebaseProjectId:
    Type: String
  FirebaseStorageBucket:
    Type: String
  FirebaseMessagingSenderId:
    Type: String
  FirebaseAppId:
    Type: String
  FirebaseMeasurementId:
    Type: String
  FirebaseAdminCreds:
    Type: String
  Stage:
    Type: String
  dbRegion:
    Type: String
    Default: us-east-1
  dbEndpoint:
    Type: String
    Default: https://dynamodb.us-east-1.amazonaws.com/
  MessageQueueStreamArn:
    Type: String
  messageQueueResourceName:
    Type: String
    Default: MessageQueue
  JoinRequestQueue:
    Type: String
    Default: 0B39C186-89FB-4158-9CF3-2FBFBCF2A6B9
  ResourceAccountId:
    Type: String
  ResourceRegion:
    Type: String
    Default: us-east-1
  DbAccessKeyId:
    Type: String
    Default: ""
  DbSecretAccessKey:
    Type: String
    Default: ""


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30    
    MemorySize: 2048

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    # LoggingConfig:
    #   LogFormat: JSON

    Environment:
      Variables:
        FirebaseApiKey: !Ref FirebaseApiKey
        FirebaseAuthDomain: !Ref FirebaseAuthDomain
        FirebaseProjectId: !Ref FirebaseProjectId
        FirebaseStorageBucket: !Ref FirebaseStorageBucket
        FirebaseMessagingSenderId: !Ref FirebaseMessagingSenderId
        FirebaseAppId: !Ref FirebaseAppId
        FirebaseMeasurementId: !Ref FirebaseMeasurementId
        FirebaseAdminCreds: !Ref FirebaseAdminCreds
        Stage: !Ref Stage
        dbRegion: !Ref dbRegion
        dbEndpoint: !Ref dbEndpoint
        dbTableName: User
        DbAccessKeyId: !Ref DbAccessKeyId
        DbSecretAccessKey: !Ref DbSecretAccessKey
        messageQueueResourceName: !Ref messageQueueResourceName
        MessageQueueStreamArn: !Ref MessageQueueStreamArn
        RtRegion: !Sub ${AWS::Region}
        AwsAccountId: !Sub ${AWS::AccountId}
        ResourceAccountId: !Ref ResourceAccountId

Resources:
  UserServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${Stage}

  # IAM Role for Lambda to allow invocation by SNS
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-LambdaExecutionRole-${AWS::Region}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaSNSInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Permissions to create and manage logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

              # Allow Lambda to receive SNS messages
              - Effect: Allow
                Action: sns:Publish
                Resource: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:UserConnected

              # Permission for Lambda to read from DynamoDB table
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: 
                  - !Sub arn:aws:dynamodb:${ResourceRegion}:${ResourceAccountId}:table/User
                  - !Sub arn:aws:dynamodb:${ResourceRegion}:${ResourceAccountId}:table/${messageQueueResourceName}
                  - !Sub ${MessageQueueStreamArn}

  AuthenticateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/authenticate
      Handler: handler.main
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Notify:
          Type: Api
          Properties:
            Path: /users/auth
            Method: post
            RestApiId: !Ref UserServiceApi
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
        - handler.ts
        External:
        - node_modules
        - aws-sdk

  FindUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: handler.main
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Notify:
          Type: Api
          Properties:
            Path: /users
            Method: get
            RestApiId: !Ref UserServiceApi
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
        - functions/get/handler.ts
        External:
        - node_modules
        - aws-sdk
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: handler.main
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Notify:
          Type: Api
          Properties:
            Path: /users
            Method: post
            RestApiId: !Ref UserServiceApi
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
        - functions/create/handler.ts
        External:
        - node_modules
        - aws-sdk
  CreateGuestUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: handler.main
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Notify:
          Type: Api
          Properties:
            Path: /users/guests
            Method: post
            RestApiId: !Ref UserServiceApi
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
        - functions/create-guest-user/handler.ts
        External:
        - node_modules
        - aws-sdk
  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: handler.main
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Notify:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: delete
            RestApiId: !Ref UserServiceApi
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
        - functions/delete/handler.ts
        External:
        - node_modules
        - aws-sdk
  GetUserByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: handler.main
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Notify:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: get
            RestApiId: !Ref UserServiceApi
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
        - functions/getById/handler.ts
        External:
        - node_modules
        - aws-sdk
  PopulateJoinRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: handler.main
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Notify:
          Type: DynamoDB
          Properties:
            Stream: !Sub ${MessageQueueStreamArn}
            MaximumRetryAttempts: 3
            MaximumRecordAgeInSeconds: 60
            StartingPosition: LATEST
            Enabled: true
            FilterCriteria:
              Filters:
                - Pattern: !Sub "{\"eventName\":[\"INSERT\"],\"dynamodb\":{\"Keys\":{\"queueName\":{\"S\":[\"${JoinRequestQueue}\"]}}}}"
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
        - functions/populate-join-request/handler.ts
        External:
        - node_modules
        - aws-sdk
        

