AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  user-service-database

  SAM Template for user-service database

Parameters:
  dbRegion:
    Type: String
  StagingLambdaExecutionRoleArn:
    Type: String

Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: User
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableClass: STANDARD
      ResourcePolicy:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                AWS: 
                  - !Sub ${StagingLambdaExecutionRoleArn}/user-service-AuthenticateFunction-I9X4qVReaOAe
                  - !Sub ${StagingLambdaExecutionRoleArn}/user-service-CreateGuestUserFunction-sYgdTRhvwpsO
                  - !Sub ${StagingLambdaExecutionRoleArn}/user-service-CreateUserFunction-VdEYqB8Hpk9u
                  - !Sub ${StagingLambdaExecutionRoleArn}/user-service-DeleteUserFunction-QaxWuEzysBYK
                  - !Sub ${StagingLambdaExecutionRoleArn}/user-service-FindUsersFunction-EvosYnUiKFfD
                  - !Sub ${StagingLambdaExecutionRoleArn}/user-service-GetUserByIdFunction-E29XCpRL00uN
                  - !Sub ${StagingLambdaExecutionRoleArn}/user-service-PopulateJoinRequestFunction-8pdAy0faY0oy
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: 
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/User
