name: Deploy Production

on:
  pull_request:
    branches:
      - main
      - releases/**

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Create Common Parameter Overrides
      run: | 
        params=
        params="Stage=production ${params}"
        params="QueueStageName=production ${params}"
        params="messageQueueResourceName=MessageQueue ${params}"
        params="dbTableName=User ${params}"
        params="dbRegion=us-east-1 ${params}"
        params="dbEndpoint=https://dynamodb.us-east-1.amazonaws.com/ ${params}"
        params="MessageQueueStreamArn=${{ secrets.MESSAGE_QUEUE_ARN_PRODUCTION }} ${params}"
        params="FirebaseApiKey=${{ secrets.FIREBASE_API_KEY_PRODUCTION }} ${params}"
        params="FirebaseAuthDomain=${{ secrets.FIREBASE_AUTH_DOMAIN_PRODUCTION }} ${params}"
        params="FirebaseProjectId=${{ secrets.FIREBASE_PROJECT_ID_PRODUCTION }} ${params}"
        params="FirebaseStorageBucket=${{ secrets.FIREBASE_STORAGE_BUCKET_PRODUCTION }} ${params}"
        params="FirebaseMessagingSenderId=${{ secrets.FIREBASE_MESSAGING_SENDER_ID_PRODUCTION }} ${params}"
        params="FirebaseAppId=${{ secrets.FIREBASE_APP_ID_PRODUCTION }} ${params}"
        params="FirebaseMeasurementId=${{ secrets.FIREBASE_MEASUREMENT_ID_PRODUCTION }} ${params}"
        params="FirebaseAdminCreds=${{ secrets.FIREBASE_ADMIN_CREDS_PRODUCTION }} ${params}"
        echo $params > parameters.cfg

    - uses: actions/setup-python@v3
    - uses: aws-actions/setup-sam@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SPLITSIES_DEPLOY_ACCESS_KEY_ID_PROD }}
        aws-secret-access-key: ${{ secrets.SPLITSIES_DEPLOY_SECRET_KEY_PROD }}
        aws-region: us-east-1

    - run: npm ci

    - run: npm run build

    - name: Deploy to us-east-1 (SAM Deploy)
      run: |
        PARAMETERS=$(cat parameters.cfg)
        sam deploy --stack-name user-service \
        --region us-east-1 \
        --no-confirm-changeset \
        --no-fail-on-empty-changeset \
        --parameter-overrides $PARAMETERS

    - run: npm ci
      working-directory: ./database
      
    - run: sam build
      working-directory: ./database

    - run: |
        sam deploy --stack-name user-service-database \
        --no-confirm-changeset \
        --no-fail-on-empty-changeset        
      working-directory: ./database

    - run: npm ci
      working-directory: ./database/staging-permissions
      
    - run: sam build
      working-directory: ./database/staging-permissions

    - run: |
        sam deploy --stack-name user-service-database-staging-access \
        --no-confirm-changeset \
        --no-fail-on-empty-changeset \
        --parameter-overrides "dbRegion=us-east-1" "StagingUserServiceLambdaExecutionRoleArn=${{ secrets.STAGING_USER_SERVICE_LAMBDA_EXECUTION_ROLE_ARN }}"
      working-directory: ./database/staging-permissions

