name: Deploy Dev PR

on:
  pull_request:
    branches:
      - main
      - releases/**

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Create Common Parameter Overrides
      run: | 
        echo -n "\"Stage=dev\" " >> parameters.cfg
        echo -n "\"MessageQueueStreamArn=arn:ddb\" " >> parameters.cfg
        echo -n "\"messageQueueResourceName=MessageQueue\" " >> parameters.cfg
        echo -n "\"dbTableName=User\" " >> parameters.cfg
        echo -n "\"dbRegion=us-east-1\" " >> parameters.cfg
        echo -n "\"dbEndpoint=https://dynamodb.us-east-1.amazonaws.com/\" " >> parameters.cfg
        echo -n "\"FirebaseApiKey=${{ secrets.FIREBASE_API_KEY_DEV_PR }}\" " >> parameters.cfg
        echo -n "\"FirebaseAuthDomain=${{ secrets.FIREBASE_AUTH_DOMAIN_DEV_PR }}\" " >> parameters.cfg
        echo -n "\"FirebaseProjectId=${{ secrets.FIREBASE_PROJECT_ID_DEV_PR }}\" " >> parameters.cfg
        echo -n "\"FirebaseStorageBucket=${{ secrets.FIREBASE_STORAGE_BUCKET_DEV_PR }}\" " >> parameters.cfg
        echo -n "\"FirebaseMessagingSenderId=${{ secrets.FIREBASE_MESSAGING_SENDER_ID_DEV_PR }}\" " >> parameters.cfg
        echo -n "\"FirebaseAppId=${{ secrets.FIREBASE_APP_ID_DEV_PR }}\" " >> parameters.cfg
        echo -n "\"FirebaseMeasurementId=${{ secrets.FIREBASE_MEASUREMENT_ID_DEV_PR }}\" " >> parameters.cfg
        echo -n "\"FirebaseAdminCreds=${{ secrets.FIREBASE_ADMIN_CREDS_DEV_PR }}\" " >> parameters.cfg
        echo -n "\"ResourceAccountId=${{ secrets.DEV_ACCOUNT_ID }}\" " >> parameters.cfg
      # Note the trailing space on each parameter above.

    - uses: actions/setup-python@v3
    - uses: aws-actions/setup-sam@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SPLITSIES_DEPLOY_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.SPLITSIES_DEPLOY_SECRET_KEY_DEV }}
        aws-region: us-east-1

    - run: npm ci

    - run: sam build
    
    - name: Deploy to us-east-1 (SAM Deploy)
      run: |
        PARAMETERS=$(cat parameters.cfg)
        echo $PARAMETERS
        sam deploy --stack-name user-service \
        --region us-east-1 \
        --no-confirm-changeset \
        --no-fail-on-empty-changeset \
        --parameter-overrides $PARAMETERS
      # "Stage=dev" \
      # "dbRegion=us-east-1" \
      # "dbEndpoint=https://dynamodb.us-east-1.amazonaws.com/" \
      # "dbTableName=User" \
      # "messageQueueResourceName=Splitsies-MessageQueue-dev-pr" \
      # "MessageQueueStreamArn=${{ secrets.MESSAGE_QUEUE_ARN_DEV_PR }}" \
      # "FirebaseApiKey=${{ secrets.FIREBASE_API_KEY_DEV_PR }}" \
      # "FirebaseAuthDomain=${{ secrets.FIREBASE_AUTH_DOMAIN_DEV_PR }}" \
      # "FirebaseProjectId=${{ secrets.FIREBASE_PROJECT_ID_DEV_PR }}" \
      # "FirebaseStorageBucket=${{ secrets.FIREBASE_STORAGE_BUCKET_DEV_PR }}" \
      # "FirebaseMessagingSenderId=${{ secrets.FIREBASE_MESSAGING_SENDER_ID_DEV_PR }}" \
      # "FirebaseAppId=${{ secrets.FIREBASE_APP_ID_DEV_PR }}" \
      # "FirebaseMeasurementId=${{ secrets.FIREBASE_MEASUREMENT_ID_DEV_PR }}" \
      # "FirebaseAdminCreds=${{ secrets.FIREBASE_ADMIN_CREDS_DEV_PR }}"  \
      # "ResourceAccountId=${{ secrets.DEV_ACCOUNT_ID }}"

    # - run: npm ci
    #   working-directory: ./database
      
    # - run: sam build
    #   working-directory: ./database

    # - run: |
    #     sam deploy --stack-name user-service-database \
    #     --no-confirm-changeset \
    #     --no-fail-on-empty-changeset        
    #   working-directory: ./database



    # - name: serverless deploy
    #   uses: serverless/github-action@v3.1
    #   with:
    #     args: deploy --stage dev-pr \
    #         --param="QUEUE_STAGE_NAME=devpr" \
    #         --param="DB_REGION=us-east-1" \
    #         --param="FIREBASE_VPC_MODE=false" \
    #         --param="DB_SCAN_LIMIT=25" \
    #         --param="DB_ENDPOINT= https://dynamodb.us-east-1.amazonaws.com/" \
    #         --param="FIREBASE_DEV_MODE=false" \
    #         --param="DB_TABLE_NAME=Splitsies-User-dev-pr" \
    #         --param="MESSAGE_QUEUE_RESOURCE_NAME=Splitsies-MessageQueue-dev-pr" \
    #         --param="INTERNAL_API_KEY=${{ secrets.INTERNAL_API_KEY }}" \
    #         --param="DB_ACCESS_KEY_ID=${{ secrets.DB_ACCESS_KEY_ID }}" \
    #         --param="DB_SECRET_ACCESS_KEY=${{ secrets.DB_SECRET_ACCESS_KEY }}" \
    #         --param="MESSAGE_QUEUE_ARN=${{ secrets.MESSAGE_QUEUE_ARN_DEV_PR }}" \
    #         --param="FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN_DEV_PR }}" \
    #         --param="FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID_DEV_PR }}" \
    #         --param="FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID_DEV_PR }}" \
    #         --param="FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID_DEV_PR }}" \
    #         --param="FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY_DEV_PR }}" \
    #         --param="FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET_DEV_PR }}" \
    #         --param="FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID_DEV_PR }}" \
    #         --param="FIREBASE_ADMIN_CREDS=${{ secrets.FIREBASE_ADMIN_CREDS_DEV_PR }}"



      # env:
      #   SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      #   AWS_ACCESS_KEY_ID: ${{ secrets.SPLITSIES_DEPLOY_ACCESS_KEY_ID_DEV }}
      #   AWS_SECRET_ACCESS_KEY: ${{ secrets.SPLITSIES_DEPLOY_SECRET_KEY_DEV }}