name: Deploy Staging

on:
  pull_request:
    branches:
      - main
      - releases/**

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Create Common Parameter Overrides
      run: | 
        params=
        params="Stage=staging ${params}"
        params="QueueStageName=dev ${params}"
        params="messageQueueResourceName=MessageQueue ${params}"
        params="dbTableName=User ${params}"
        params="dbRegion=us-east-1 ${params}"
        params="dbEndpoint=https://dynamodb.us-east-1.amazonaws.com/ ${params}"
        params="MessageQueueStreamArn=${{ secrets.MESSAGE_QUEUE_ARN_STAGING }} ${params}"
        params="FirebaseApiKey=${{ secrets.FIREBASE_API_KEY_STAGING }} ${params}"
        params="FirebaseAuthDomain=${{ secrets.FIREBASE_AUTH_DOMAIN_STAGING }} ${params}"
        params="FirebaseProjectId=${{ secrets.FIREBASE_PROJECT_ID_STAGING }} ${params}"
        params="FirebaseStorageBucket=${{ secrets.FIREBASE_STORAGE_BUCKET_STAGING }} ${params}"
        params="FirebaseMessagingSenderId=${{ secrets.FIREBASE_MESSAGING_SENDER_ID_STAGING }} ${params}"
        params="FirebaseAppId=${{ secrets.FIREBASE_APP_ID_STAGING }} ${params}"
        params="FirebaseMeasurementId=${{ secrets.FIREBASE_MEASUREMENT_ID_STAGING }} ${params}"
        params="FirebaseAdminCreds=${{ secrets.FIREBASE_ADMIN_CREDS_STAGING }} ${params}"
        params="ResourceAccountId=${{ secrets.PROD_ACCOUNT_ID }} ${params}"
        echo $params > parameters.cfg

    - uses: actions/setup-python@v3
    - uses: aws-actions/setup-sam@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SPLITSIES_DEPLOY_ACCESS_KEY_ID_STAGING }}
        aws-secret-access-key: ${{ secrets.SPLITSIES_DEPLOY_SECRET_KEY_STAGING }}
        aws-region: us-east-1

    - run: npm ci

    - run: npm run build

    - name: Deploy to us-east-1 (SAM Deploy)
      run: |
        PARAMETERS=$(cat parameters.cfg)
        sam deploy --stack-name user-service \
        --region us-east-1 \
        --no-confirm-changeset \
        --no-fail-on-empty-changeset \
        --parameter-overrides $PARAMETERS
